
import React, { useState } from 'react';
import { X, Copy, Check, Database, ArrowRight, Server } from 'lucide-react';

interface SupabaseWizardProps {
  onClose: () => void;
}

const SupabaseWizard: React.FC<SupabaseWizardProps> = ({ onClose }) => {
  const [copied, setCopied] = useState(false);

  const sqlSchema = `
-- 1. Districts (Tenants)
create table if not exists districts (
  id text primary key,
  name text not null,
  contact_email text,
  subscription_tier text default 'BASIC',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Buses (Fleet)
create table if not exists buses (
  id uuid default gen_random_uuid() primary key,
  district_id text references districts(id),
  bus_number text not null,
  driver_name text,
  status text default 'IDLE',
  capacity int default 60,
  vin text,
  license_plate text,
  last_maintenance_date date,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Students
create table if not exists students (
  id text primary key, -- School issued ID
  district_id text references districts(id),
  first_name text not null,
  last_name text not null,
  grade int,
  school_name text,
  rfid_tag text,
  assigned_bus_id uuid references buses(id),
  parent_email text,
  status text default 'UNKNOWN',
  last_scan_time timestamp with time zone,
  last_scan_location text
);

-- 4. Maintenance Tickets
create table if not exists maintenance_tickets (
  id uuid default gen_random_uuid() primary key,
  bus_id uuid references buses(id),
  issue_description text,
  priority text default 'MEDIUM',
  status text default 'OPEN',
  reported_by text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  resolved_at timestamp with time zone
);

-- 5. GPS Telemetry Logs (High Volume)
create table if not exists telemetry_logs (
  id bigint generated by default as identity primary key,
  bus_id uuid references buses(id),
  lat float,
  lng float,
  speed float,
  heading float,
  timestamp timestamp with time zone default timezone('utc'::text, now())
);

-- ENABLE RLS and ADD POLICIES (Fix for "Permission Denied" errors)
-- Note: These are permissive policies for DEMO purposes. Restrict in production.

alter table districts enable row level security;
create policy "Public Access Districts" on districts for all using (true);

alter table buses enable row level security;
create policy "Public Access Buses" on buses for all using (true);

alter table students enable row level security;
create policy "Public Access Students" on students for all using (true);

alter table maintenance_tickets enable row level security;
create policy "Public Access Tickets" on maintenance_tickets for all using (true);
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/80 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl h-[85vh] flex flex-col overflow-hidden font-sans">
        
        {/* Header */}
        <div className="bg-slate-900 p-6 flex justify-between items-start shrink-0">
            <div className="text-white">
                <h2 className="text-2xl font-bold flex items-center gap-3">
                    <Database className="text-green-400" /> Supabase Setup Wizard
                </h2>
                <p className="text-slate-400 mt-1">Initialize your cloud database schema.</p>
            </div>
            <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
                <X size={24} />
            </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-8 bg-slate-50 flex flex-col gap-8">
            
            {/* Step 1 */}
            <div className="flex gap-6">
                <div className="w-10 h-10 rounded-full bg-blue-100 text-blue-600 font-bold flex items-center justify-center shrink-0 text-lg border border-blue-200">1</div>
                <div className="flex-1">
                    <h3 className="text-lg font-bold text-slate-800 mb-2">Open SQL Editor</h3>
                    <p className="text-slate-600 text-sm mb-4">
                        Log in to your Supabase Dashboard, select your project, and navigate to the <strong>SQL Editor</strong> tab in the left sidebar.
                    </p>
                    <div className="bg-white border border-slate-200 p-4 rounded-lg inline-flex items-center gap-2 text-xs font-mono text-slate-500">
                        <Server size={14} /> dashboard.supabase.com/project/_/sql
                    </div>
                </div>
            </div>

            {/* Step 2 */}
            <div className="flex gap-6">
                <div className="w-10 h-10 rounded-full bg-blue-100 text-blue-600 font-bold flex items-center justify-center shrink-0 text-lg border border-blue-200">2</div>
                <div className="flex-1">
                    <h3 className="text-lg font-bold text-slate-800 mb-2">Run Schema Script</h3>
                    <p className="text-slate-600 text-sm mb-4">
                        Copy the SQL code below and paste it into the editor. Click <strong>RUN</strong> to create the necessary tables for RideSmart.
                    </p>
                    
                    <div className="relative bg-slate-800 rounded-xl overflow-hidden border border-slate-700 shadow-lg">
                        <div className="flex justify-between items-center px-4 py-2 bg-black/30 border-b border-slate-700">
                            <span className="text-xs font-mono text-slate-400">init_schema.sql</span>
                            <button 
                                onClick={handleCopy}
                                className="flex items-center gap-2 text-xs font-bold text-blue-400 hover:text-blue-300 transition-colors"
                            >
                                {copied ? <Check size={14} /> : <Copy size={14} />}
                                {copied ? 'Copied!' : 'Copy Code'}
                            </button>
                        </div>
                        <pre className="p-4 text-xs font-mono text-green-300 overflow-x-auto h-64 custom-scrollbar leading-relaxed">
                            {sqlSchema}
                        </pre>
                    </div>
                </div>
            </div>

             {/* Step 3 */}
             <div className="flex gap-6">
                <div className="w-10 h-10 rounded-full bg-blue-100 text-blue-600 font-bold flex items-center justify-center shrink-0 text-lg border border-blue-200">3</div>
                <div className="flex-1">
                    <h3 className="text-lg font-bold text-slate-800 mb-2">Connect App</h3>
                    <p className="text-slate-600 text-sm">
                        Go to <strong>Project Settings > API</strong>. Copy the <code>Project URL</code> and <code>anon public key</code> and paste them into the RideSmart Infrastructure tab.
                    </p>
                </div>
            </div>

        </div>

        {/* Footer */}
        <div className="p-6 border-t border-slate-200 bg-white flex justify-end">
            <button 
                onClick={onClose}
                className="px-6 py-3 bg-slate-900 text-white font-bold rounded-xl hover:bg-slate-800 transition-all flex items-center gap-2 shadow-lg"
            >
                I've Run the Script <ArrowRight size={18} />
            </button>
        </div>
      </div>
    </div>
  );
};

export default SupabaseWizard;
